import '@weyneshof/util/global.css';

import { Roboto } from 'next/font/google';

const roboto = Roboto({ weight: '500', subsets: ['latin'] });
export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body
        className={`${roboto.className} h-screen w-screen bg-gray-100 dark:bg-gray-800 `}
      >
        {children}
      </body>
    </html>
  );
}
